### ISSUE TITLE
Yahoo discontinued the Answers API

### ISSUE THREAD

**Issue by liujuliet** [kevinAlbs/YahooAnswersScraper#2]
https://forums.developer.yahoo.net/discussion/comment/21866/#Comment_21866

**Comment by kevinAlbs** [comment]
Yes, this has been brought to my attention with #1. I'll ping the author to see if he's interested in updating the PR. If not, then I'll add a warning or remove this repository. Sorry for any confusion caused.

**Comment by kevinAlbs** [comment]
Alright, I updated the readme with a warning. Thanks for reminding me about this.
